name: fmt

on: [push, pull_request]

jobs:
  fmt:
    name: Check code formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v1
        with:
          node-version: "14"

      - name: Install yarn
        run: npm i -g yarn

      - name: Install dependencies
        run: yarn

      - name: Check fmt
        run: yarn fmt:check
